-- AlterEnum
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_SECONDE1';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_SECONDE2';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_PREMIERE1';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_PREMIERE2';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_TERMINALE1';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_TERMINALE2';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_BT1_S1';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_BT1_S2';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_BT2_S1';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_BT2_S2';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_BT3_S1';
ALTER TYPE "TypePieceJointe" ADD VALUE 'BULLETIN_NOTES_BT3_S2';
